name: Update Repo Wiki

on:
  push:
    paths:
      - hotwash/**  
  workflow_dispatch:
  
jobs:
  update-wiki:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.5

      - name: Update Wiki
        uses: OrlovM/Wiki-Action@master
        with:
          path: reports
          token: ${{ secrets.GITHUB_TOKEN }}
